[project]
name = "drug-complaint-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dtale>=3.18.2",
    "pandas>=2.3.1",
]
